# Tensor

In [4]:
import torch as tr
import torch.nn.functional as F
import numpy as np

t1 = tr.Tensor(np.ones((2,3)))
print('t1:\n',t1)
print('t1.numpy:\n',t1.numpy())
t2 = tr.ones((2,3))
print('t2:\n',t2)
t3 = tr.zeros((2,3))
print('t3:\n',t3)
t4 = t1.long()
# .short, .int,
print('t4:\n',t4)
t1[1,2] = 999
print('t1:\n',t1)

# the from_numpy will inherit the type of numpy array.
t5=tr.from_numpy(np.zeros((3,4),dtype='float64'))
print('t5:\n',t5)

t6 = tr.randn((3,3))
print('t6:\n',t6)

N, C = 5, 4
t7 = tr.LongTensor(N, 8, 8).random_(0, C)
input = tr.autograd.Variable(tr.randn(3, 5))
print('input:\n',input)
print('t7:\n',t7)

t8 = tr.FloatTensor([np.ones((2,)),np.ones((2,)),np.ones((2,))])
print('t8:\n',t8)

t9 = t8.view(-1)
print('t9:\n',t9)
print('t8:\n',t8)

t1:
 
 1  1  1
 1  1  1
[torch.FloatTensor of size 2x3]

t1.numpy:
 [[1. 1. 1.]
 [1. 1. 1.]]
t2:
 
 1  1  1
 1  1  1
[torch.FloatTensor of size 2x3]

t3:
 
 0  0  0
 0  0  0
[torch.FloatTensor of size 2x3]

t4:
 
 1  1  1
 1  1  1
[torch.LongTensor of size 2x3]

t1:
 
   1    1    1
   1    1  999
[torch.FloatTensor of size 2x3]

t5:
 
 0  0  0  0
 0  0  0  0
 0  0  0  0
[torch.DoubleTensor of size 3x4]

t6:
 
 1.2235 -0.1828 -0.6240
-1.7459 -1.0781 -0.0315
-1.1519  0.0393  1.1664
[torch.FloatTensor of size 3x3]

input:
 Variable containing:
-1.3099 -0.0280 -0.4209  0.2763  0.2660
-0.4541  0.2253 -0.7899  0.8581 -0.9677
 0.7413  0.6453 -0.1231 -0.9948 -1.7731
[torch.FloatTensor of size 3x5]

t7:
 
(0 ,.,.) = 
   3   1   3   0   0   2   3   1
   0   2   1   1   0   3   0   2
   2   3   3   1   3   2   0   3
   2   0   1   3   2   2   2   2
   1   3   2   2   2   1   0   0
   0   1   3   1   1   2   0   3
   1   2   0   1   1   1   3   0
   3   3   1   1   0   3   0   3

(1 ,.,.) = 
   3

In [3]:
# t3.cuda() can put data to gpu

# Variable

In [4]:
t1 = tr.FloatTensor([[1,2],[3,4]])
v1 = tr.autograd.Variable(t1,requires_grad=True)

In [5]:
# mean through a specific axis
v= tr.mean(v1*v1,dim=1)
print(v.data)


  2.5000
 12.5000
[torch.FloatTensor of size 2]



# gradient

In [6]:
from torch.autograd import Variable

In [7]:
x=Variable(tr.ones(2,2),requires_grad=True)
y=tr.mul(x,x)
out = tr.mean(y)
print(out)
out.backward(tr.FloatTensor([1])) # or out.backward()
print(x.grad)

Variable containing:
 1
[torch.FloatTensor of size 1]

Variable containing:
 0.5000  0.5000
 0.5000  0.5000
[torch.FloatTensor of size 2x2]



In [8]:
x=Variable(tr.ones(2,2),requires_grad=True)
y=tr.mul(x,x)
# 0.1 is learning rate, multiplied before gradient.
y.backward(tr.FloatTensor([[0.1,0.1],[0.1,0.1]]))
print(x.grad)

Variable containing:
 0.2000  0.2000
 0.2000  0.2000
[torch.FloatTensor of size 2x2]



# Data

In [10]:
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import numpy as np

class myDataset(Dataset):
    def __init__(self):
        self.feature_data = np.ones((1000,20),dtype='float32')
        self.length = 1000
        self.label_data = np.random.randint(low=0,high=2,size=(1000,10)).astype('float32')
    def __len__(self):
        return self.length
    def __getitem__(self,idx):
        data = (self.feature_data[idx],self.label_data[idx])
        return data
data = myDataset()
dataiter = DataLoader(data,batch_size=20,shuffle=False)
print('======')
for batch_id,(X,Y_) in enumerate(dataiter):
    print(X)
    print(Y_)
    break



Columns 0 to 12 
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1    

In [26]:
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import numpy as np

class myDataset(Dataset):
    def __init__(self):
        self.feature_data = np.ones((998,20),dtype='float32')
        self.length = 998
        self.label_data = np.random.randint(low=0,high=2,size=(1000,10)).astype('float32')
    def __len__(self):
        return self.length
    def __getitem__(self,idx):
        data = (self.feature_data[idx],self.label_data[idx])
        return data
data = myDataset()
dataiter = DataLoader(data,batch_size=100,shuffle=False)
print('======')
for X,y_ in dataiter:
    print(X.size())
print('when the rest of data is not enough for a batch, all of the rest will be returned')

torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([98, 20])
when the rest of data is not enough for a batch, all of the rest will be returned


In [1]:
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import numpy as np

class myDataset(Dataset):
    def __init__(self):
        self.feature_data = np.ones((1000,20),dtype='float32')
        self.length = 1000
        self.label_data = np.random.randint(low=0,high=2,size=(1000,)).astype('float32')
    def __len__(self):
        return self.length
    def __getitem__(self,idx):
        data = (self.feature_data[idx],self.label_data[idx])
        print('================')
        print(data)
        return data
data = myDataset()
dataiter = DataLoader(data,batch_size=20,shuffle=False)
print('======')
for X,Y_ in dataiter:
    print(X)
    print(Y_)
    break

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.], dtype=float32), 0.0)
(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.], dtype=float32), 1.0)
(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.], dtype=float32), 1.0)
(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.], dtype=float32), 1.0)
(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.], dtype=float32), 1.0)
(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.], dtype=float32), 0.0)
(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.], dtype=float32), 1.0)
(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.], dtype=float32), 0.0)
(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 

## initiate Dataset from outside

In [2]:
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import numpy as np

class myDataset(Dataset):
    def __init__(self,features,labels):
        self.feature_data = features
        self.length = len(features)
        self.label_data = labels 
    def __len__(self):
        return self.length
    def __getitem__(self,idx):
        data = (self.feature_data[idx],self.label_data[idx])
        return data

features = np.ones((1000,20),dtype='float32')
labels = np.random.randint(low=0,high=2,size=(1000,)).astype('float32')

data = myDataset(features, labels)
dataiter = DataLoader(data,batch_size=20,shuffle=False)
for X,Y_ in dataiter:
    print(X)
    print(Y_)
    break



Columns 0 to 12 
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1    

## complete sample of Dataset and DataLoader

In [15]:
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import pickle

# TODO: need to normalize data
class myDataset(Dataset):
    def __init__(self,data):
        self.data = data
        self.length = len(data)

    def __len__(self):
        return self.length

    def __getitem__(self, index):
        instance = self.data[index]
        return instance

class DataFeeder:
    def __init__(self,data_config):
        self.data_config = data_config
        self.train_data,self.test_data=self.loader()

    def loader(self):
        with open(self.data_config['data_filePath'],'rb') as f:
            data = pickle.load(f)
        return data['train_data'], data['test_data']

    def train_feeder(self):
        dataiter = DataLoader(myDataset(self.train_data),batch_size=self.data_config['batch_size'],shuffle='True')
        return enumerate(dataiter)

    def test_feeder(self):
        data = DataLoader(myDataset(self.test_data),batch_size=len(self.test_data),shuffle='True')
        return data

# Repeat&expand

In [34]:
import torch as tr
t = tr.Tensor([[1,2,3]])
t = t.repeat(4,1)
print(t)


 1  2  3
 1  2  3
 1  2  3
 1  2  3
[torch.FloatTensor of size 4x3]



# +, - , *, /, reduce sum, reduce max, reduce mean

In [5]:
import torch as tr
import numpy as np
v1 = tr.Tensor(np.ones((3,3,4)))
v2 = tr.Tensor(np.ones((3,4))*2)
t = tr.mul(v1,v2)
print('mul\n',t)

t = tr.add(v1,-v2)
print('subtract\n',t)

t = tr.sqrt(v2)
print('sqrt\n',t)

t = v2.sum(1)
print('reduce_sum\n',t)

t = v1.mean(1)
print('reduce_mean:\n',t)
print('reduce_mean size:\n',t.size())


mul
 
(0 ,.,.) = 
  2  2  2  2
  2  2  2  2
  2  2  2  2

(1 ,.,.) = 
  2  2  2  2
  2  2  2  2
  2  2  2  2

(2 ,.,.) = 
  2  2  2  2
  2  2  2  2
  2  2  2  2
[torch.FloatTensor of size 3x3x4]

subtract
 
(0 ,.,.) = 
 -1 -1 -1 -1
 -1 -1 -1 -1
 -1 -1 -1 -1

(1 ,.,.) = 
 -1 -1 -1 -1
 -1 -1 -1 -1
 -1 -1 -1 -1

(2 ,.,.) = 
 -1 -1 -1 -1
 -1 -1 -1 -1
 -1 -1 -1 -1
[torch.FloatTensor of size 3x3x4]

sqrt
 
 1.4142  1.4142  1.4142  1.4142
 1.4142  1.4142  1.4142  1.4142
 1.4142  1.4142  1.4142  1.4142
[torch.FloatTensor of size 3x4]

reduce_sum
 
 8
 8
 8
[torch.FloatTensor of size 3]

reduce_mean:
 
 1  1  1  1
 1  1  1  1
 1  1  1  1
[torch.FloatTensor of size 3x4]

reduce_mean size:
 torch.Size([3, 4])


# Repeat&Expand

In [7]:
import torch as tr
import numpy as np
v1 = tr.Tensor(np.array([1,2,3]))
v2 = tr.unsqueeze(v1,dim=1)
print()
v3 = v2.expand(-1,3)
print(v3)



 1  1  1
 2  2  2
 3  3  3
[torch.FloatTensor of size 3x3]

